### PR TITLE
Fix disconnection problems

### PR DESCRIPTION
**Pull request by emilianya**
Solve your problems with this additional Context! Only 19.98€!!
Order today and get it for free

### CODE REVIEW

**Comment by nyakase** [comment]
That deploy is going to be so useful (I still didn't fill its tummy with api keys)

**Review by nyakase — APPROVED** [review]
> Solve your problems with this additional Context! Only 19.98€!!
[insert stop doing math meme template]

**Comment by nyakase** [comment]
Ever thought about how pretty the github ui is

**Comment by emilianya** [comment]
yea

**Comment by nyakase** [comment]
aw

**Pull request merged**
